apiVersion: skaffold/v1alpha2
kind: Config
build:
  tagPolicy:
    envTemplate:
      template: "{{.DOCKER_REGISTRY}}/venkatvar/java-6617:{{.VERSION}}"
  artifacts:
  - imageName: changeme
    workspace: .
    docker: {}
  local: {}
deploy:
  kubectl:
    manifests:
profiles:
- name: dev
  build:
    tagPolicy:
      envTemplate:
        template: "{{.DOCKER_REGISTRY}}/venkatvar/java-6617:{{.DIGEST_HEX}}"
    artifacts:
    - docker: {}
    local: {}
  deploy:
    helm:
      releases:
      - name: java-6617
        chartPath: charts/java-6617
        setValueTemplates:
          image.repository: "{{.DOCKER_REGISTRY}}/venkatvar/java-6617"
          image.tag: "{{.DIGEST_HEX}}"
